# Copyright (C) 2026 the Kingdom Come: Together contributors (AUTHORS). SPDX-License-Identifier: GPL-3.0-only
# GPLv3 section 7 additional terms: NOTICE. This project's own code only; Kingdom Come: Deliverance II and its
# content belong to Warhorse Studios and PLAION. Unofficial, free, not affiliated with or endorsed by them.
"""WO-166 live harness (never shipped). Unattended: no focus change, no key press, no game action injected; the game runs in the
background; the throwaway playline only. Uses run165.py (game / inject / relay / peer / agent / stop) and sit165.py's readers.

usage:
  python run166.py fight <tag> <agent.dll> <minutes> <delay_ms> [snap on|off]
        joiner role: 3 copies round the player (the WO-165 C4 rings), a swing every 1.5 s (verdicts from the synthetic host), the
        host's weather twice (W164 kind 5) and a quest checkpoint that differs from this game's (kvalitaMece) -- the C2 / C3 / C4 / W1 /
        T2 checks; writes logs/run166.<tag>.json
  python run166.py loot <n>            L1: n loot cycles on a corpse copy (open the game's own loot screen through the mod's path, a host
                                       update while it is open, close it) -- run inside a joiner run (the agent and peer up)
  python run166.py talk <npc>          T3: a press on a paused copy through the game's own talk action (scripted: the request may not start)
  python run166.py status              the WO-166 counters of the Lua and the DLL
"""
import json, os, re, subprocess, sys, time
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import live
import run165 as R
import sit165 as S

ROW = '3e27732b-b152-4a27-97d2-1ebba717a588'   # the WO-165 plans' swing row (a catalogued attack with its own timings)
QPATH = 'Barbora.trosecko.kovar.hibernace.porovnani_kvality.kvalitaMece'


def c4_head():
    """The WO-165 C4 plan's head: the ghost and the three ring fighters with their combat state."""
    keep = []
    for l in open(os.path.join(live.HERE, 'plans', 'plan.wo165.c4.txt')):
        if l.startswith(('ghost ', 'fightz ', 'ncombat ')):
            if l.startswith('ncombat '):
                f = l.split(); f[2] = '99999'; l = ' '.join(f) + '\n'
            keep.append(l.rstrip('\n'))
    return keep


def plan_fight(tag, minutes):
    L = ['# WO-166 (generated by run166.py): joiner role, 3 copies round the player, a swing every 1.5 s, the host\'s weather, a checkpoint',
         'start 20'] + c4_head()
    npcs = ['ttkc_man_31', 'ttkc_man_30', 'ttkc_man_3']
    t, i = 20.0, 0
    end = 20 + minutes * 60
    while t < end:
        v = 'hit 0 1' if i % 2 == 0 else 'blocked 0 2'   # stamina only: a long run never kills the player (the life gate refuses while down)
        L.append('swingat %.1f %s local %s 220 %s' % (t, npcs[i % 3], ROW, v))
        t += 1.5; i += 1
    L += ['w164 25 5 0.62 semicloudy_clear_B', 'w164 %d 5 0.10 cloudy_no_rain' % min(end - 20, 140),
          'qcp 30 3 %s' % QPATH, 'qcp 75 3 %s' % QPATH]
    path = os.path.join(live.LOGS, 'plan.run166.%s.txt' % tag)
    open(path, 'w').write('\n'.join(L) + '\n')
    return path, i


def window_lines(path, since, until):
    out = []
    with open(path, encoding='utf-8', errors='replace') as f:
        for l in f:
            if l.startswith('[') and since <= l[1:9] <= until: out.append(l)
    return out


def fight(tag, agent_dll, minutes, delay, snap, strikes=''):
    R.stop('agent'); R.stop('peer')
    time.sleep(7)
    plan, nswings = plan_fight(tag, minutes)
    z = S.ground(2343.8, 2049.14)
    for _ in range(3):   # a long teleport lands before the ground's physics: held on the terrain until steady (kcd2-teleport-falls-through)
        live.lua('player:SetWorldPos({x=2343.8, y=2049.14, z=%f})' % (z + 0.3))
        time.sleep(1.5)
    opts = ['--duration', str(int(minutes * 60 + 40)), '--claim-host']
    if delay > 0: opts += ['--delay-ms', str(delay)]
    R.peer('r166' + tag, plan, opts)
    t_peer = time.time()
    R.agent('r166' + tag, agent_dll, ['KCDMP_TEST_JOINER_IN_WORLD=1'])
    time.sleep(12)
    live.cmd('mp_leash off')
    if snap in ('on', 'off'): live.cmd('mp_snap_fix ' + snap)
    if strikes in ('on', 'off'): live.cmd('mp_copy_strikes ' + strikes)
    time.sleep(max(0, t_peer + 20 - time.time()))
    since = time.strftime('%H:%M:%S')
    time.sleep(minutes * 60 + 4)
    live.cmd('mp_w166_status')
    time.sleep(62)   # the agent's minute lines (MP-WO166 native, MP-WO161-STATS)
    until = time.strftime('%H:%M:%S')
    st = R.load_state()
    agentlog = st['agentlog']
    native = os.path.join(live.LOGS, 'run166.%s.native.log' % tag)
    open(native, 'w', encoding='utf-8').writelines(window_lines(live.NLOG, since, until))
    a = open(agentlog, encoding='utf-8', errors='replace').read()
    res = {'tag': tag, 'minutes': minutes, 'delay_ms': delay, 'snap': snap, 'strikes': strikes or 'on', 'swings_planned': nswings, 'window': [since, until]}
    hits = re.findall(r'WO161-HIT victim=me .*', a)
    res['wo161_hits'] = len(hits)
    res['applied_dup'] = sum(1 for h in hits if 'applied=dup' in h)
    reasons = {}
    for h in hits:
        m = re.search(r'shown=(\w+) reason=([\w-]+)', h)
        if m: reasons[m.group(1) + ':' + m.group(2)] = reasons.get(m.group(1) + ':' + m.group(2), 0) + 1
    res['shown_reasons'] = reasons
    res['strike_lines'] = len(re.findall(r'WO166-STRIKE', a))
    nat = open(native, encoding='utf-8', errors='replace').read()
    res['strike_begin'] = len(re.findall(r'WO166-STRIKE npc=\S+ window=\d+ begin', nat))
    res['strike_mid_striking'] = len(re.findall(r'WO166-STRIKE npc=\S+ window=\d+ mid state=0x8 ', nat))
    res['strike_mid_lines'] = len(re.findall(r'WO166-STRIKE npc=\S+ window=\d+ mid ', nat))
    res['strike_player_opp_copy'] = len(re.findall(r'player_opponent=this-copy', nat))
    res['strike_end_prior_back'] = len(re.findall(r'end state_now=\S+ -> prior state back', nat))
    res['strike_switched_off'] = len(re.findall(r'WO166-STRIKE switched OFF', nat))
    res['localhit_dropped'] = len(re.findall(r'WO166-LOCALHIT dropped', nat))
    res['native_status'] = (re.findall(r'MP-WO166 native: (.*)', a) or [''])[-1][:600]
    res['qfix'] = re.findall(r'WO164-QFIX var=\S*kvalitaMece.*', a)[-3:]
    res['weather_agent'] = re.findall(r'WO166-WEATHER .*', a)[-3:]
    k = open(live.KLOG, encoding='utf-8', errors='replace').read()
    res['weather_lua'] = re.findall(r'WO166-WEATHER applied[^\n]*', k)[-3:]
    res['w166_status_lua'] = (re.findall(r'WO166-STATUS[^\n]*', k) or [''])[-1][:400]
    res['frame'] = [l[l.find('FRAME'):][:200] for l in nat.splitlines() if 'FRAME ' in l][-6:]
    out = subprocess.run([sys.executable, os.path.join(live.HERE, 'fightsnap165.py'), '--native', native, '--agent', agentlog], capture_output=True, text=True).stdout
    try:
        snapm = json.loads(out)
        res['fightsnap'] = {k2: snapm.get(k2) for k2 in ('fight', 'holds')}
    except Exception:
        res['fightsnap'] = out[:400]
    res['faults'] = len(re.findall(r'FAULT|switched OFF|faulted', nat))
    json.dump(res, open(os.path.join(live.LOGS, 'run166.%s.json' % tag), 'w'), indent=1)
    print(json.dumps(res, indent=1)[:6000])


def body_list(name):
    s = S.ask('local e=System.GetEntityByName("%s"); local t={}; if e and e.inventory then for _,w in ipairs(e.inventory:GetInventoryTable()) do local it=ItemManager.GetItem(w); if it then t[#t+1]=it.class end end end; table.sort(t); System.LogAlways("@TAG "..table.concat(t,","))' % name,
              'bl%d' % time.time_ns())
    return s or ''


def loot(n, corpse):
    """L1 in the game: the mod's own open path on a corpse copy, a host update while the game's loot screen is open, the close."""
    res = {'cycles': 0, 'deferred': 0, 'applied': 0, 'closed_by': {}, 'rewritten_under_screen': 0, 'crash': False}
    klen0 = S.klen()
    for i in range(n):
        before = body_list(corpse)
        # the joiner's loot request (BasicAIActions.OnLoot -> the W131 wrap -> W134LootRequest), then the host's answer
        live.lua('local e=System.GetEntityByName("%s"); if e then BasicAIActions.OnLoot(e, player, 1) end' % corpse)
        time.sleep(0.4)
        live.lua('KCD2MP_W134BodyState("%s", "open", 1, 1, 1, {{"b0fc8e19-af72-4771-9517-caec4f568920", 1, 1, false}, {"a856e87a-8065-4338-919d-0aff7a63341d", 1, 1, false}})' % corpse)
        time.sleep(1.2)
        opened = body_list(corpse)
        # the host looted the sword meanwhile: an update while the screen is open
        live.lua('KCD2MP_W134BodyState("%s", "update", 1, 1, 1, {{"a856e87a-8065-4338-919d-0aff7a63341d", 1, 1, false}})' % corpse)
        time.sleep(0.8)
        under = body_list(corpse)
        if under != opened: res['rewritten_under_screen'] += 1
        # the game's own close of the loot screen (its Flash element's Close; no key press)
        live.lua('UIAction.CallFunction("ItemTransfer", -1, "Close", true)')
        time.sleep(1.5)
        res['cycles'] += 1
        if not live.up(): res['crash'] = True; break
    time.sleep(2)
    lines = S.kcd_lines(r'WO166-LOOT (deferred|applied|listener)|ui_inv_screen_(in|out)', klen0)
    res['deferred'] = sum(1 for l in lines if 'WO166-LOOT deferred' in l)
    res['applied'] = sum(1 for l in lines if 'WO166-LOOT applied' in l)
    for l in lines:
        m = re.search(r'close=(\w+)', l)
        if m: res['closed_by'][m.group(1)] = res['closed_by'].get(m.group(1), 0) + 1
    res['screen_in'] = sum(1 for l in lines if 'ui_inv_screen_in' in l)
    res['screen_out'] = sum(1 for l in lines if 'ui_inv_screen_out' in l)
    res['listener'] = [l.strip()[:160] for l in lines if 'listener' in l][:2]
    res['game_up'] = live.up()
    json.dump(res, open(os.path.join(live.LOGS, 'run166.loot.json'), 'w'), indent=1)
    print(json.dumps(res, indent=1))


def talk(npc):
    klen0 = S.klen()
    live.lua('local e=System.GetEntityByName("%s"); if e then BasicAIActions.OnTalk(e, player, 1) end' % npc)
    time.sleep(8)
    for l in S.kcd_lines(r'WO166-TALK|WO137-TALK|requested dialog|Attempting to start new dialogue', klen0)[:20]:
        print(l.strip()[:220])


def status():
    live.cmd('mp_w166_status')
    time.sleep(1)
    for l in live.tail(live.KLOG, 5, r'WO166-STATUS'): print(l[:400])


def agent_lines(path, since, until):
    out = []
    with open(path, encoding='utf-8', errors='replace') as f:
        for l in f:
            if len(l) > 12 and l[2] == ':' and since <= l[:8] <= until: out.append(l)
    return out


def c1(agent_dll, guard, modes, secs):
    """C1 (host role): the synthetic joiner's figure, held in combat (gcombat), strikes a local guard (avatarfight: stamina only) so
    the guard fights it; per figure automation pattern (mp_w166_automode), the guard's committed attacks on it, the blows that land,
    and the figure's own committed actions (cap_ours)."""
    R.stop('agent'); R.stop('peer')
    time.sleep(7)
    g = S.ent_pos(guard)
    if not g: raise SystemExit('no guard ' + guard)
    gx, gy = g[0] + 1.6, g[1]
    gz = S.ground(gx, gy)
    # Henry 30 m away (no host lock-on, the guard never on Henry)
    hx, hy = g[0] - 30.0, g[1]
    hz = S.ground(hx, hy)
    for _ in range(3):
        live.lua('player:SetWorldPos({x=%f, y=%f, z=%f})' % (hx, hy, hz + 0.3)); time.sleep(1.5)
    total = len(modes) * secs + 120
    L = ['# WO-166 C1 (generated by run166.py): this machine is the HOST; the synthetic joiner\'s figure, in combat, strikes a local guard',
         'start 3', 'ghost %.2f %.2f %.2f 0 1 50 0.0005 30' % (gx, gy, gz), 'avatarfight 3 %d %s 2.0 0 3' % (total, guard),
         'gcombat 0 %d 1' % total]
    plan = os.path.join(live.LOGS, 'plan.run166.c1.txt')
    open(plan, 'w').write('\n'.join(L) + '\n')
    R.agent('r166c1', agent_dll, [])            # the agent first: in a shared world it claims host and is the authority
    time.sleep(10)
    R.peer('r166c1', plan, ['--duration', str(total + 60)])
    agentlog = R.load_state()['agentlog']
    time.sleep(25)
    res = {'guard': guard, 'secs': secs, 'modes': []}
    for m in modes:
        live.cmd('mp_w166_automode %d' % m)
        time.sleep(3)
        since = time.strftime('%H:%M:%S')
        time.sleep(secs)
        until = time.strftime('%H:%M:%S')
        nat = window_lines(live.NLOG, since, until)
        ag = agent_lines(agentlog, since, until)
        landed = sum(1 for l in nat if 'WO132-HITS npc hit on avatar' in l)
        rows = sum(1 for l in ag if 'MP-ACTION section=outbound kind=NpcAttack npc=%s ' % guard in l)
        autos = [l.split('WO121-MOTION ', 1)[1].strip()[:120] for l in nat if 'WO121-MOTION body=kcd2mp_' in l and 'combat automation' in l]
        stats = [l for l in ag if 'MP-WO121-STATS' in l]
        ours = re.findall(r'cap_ours=(\d+)', stats[-1]) if stats else []
        res['modes'].append({'mode': m, 'window': [since, until], 'guard_attack_rows': rows, 'blows_landed': landed,
                             'automation_lines': autos[-2:], 'cap_ours_end': int(ours[0]) if ours else None})
        print(json.dumps(res['modes'][-1]))
    live.cmd('mp_w166_automode 0')
    json.dump(res, open(os.path.join(live.LOGS, 'run166.c1.json'), 'w'), indent=1)


def r1s1(guard):
    """R1 + S1 (host role, the C1 run's agent and a new peer): the figure strikes the guard, the guard's blows land, the joiner dies and
    wakes (raw 0x23 / 0x3E); Henry then stands 200 m away while the figure fights on."""
    R.stop('peer')
    time.sleep(7)
    g = S.ent_pos(guard)
    gx, gy = g[0] + 1.6, g[1]
    gz = S.ground(gx, gy)
    import struct
    wake = struct.pack('<fffB', gx + 120.0, gy, S.ground(gx + 120.0, gy), 0).hex()
    L = ['# WO-166 R1/S1 (generated by run166.py)', 'start 3', 'ghost %.2f %.2f %.2f 0 1 50 0.0005 30' % (gx, gy, gz),
         'avatarfight 3 200 %s 2.0 0 3' % guard, 'gcombat 0 400 1', 'raw 60 23 -', 'raw 68 3E %s' % wake]
    plan = os.path.join(live.LOGS, 'plan.run166.r1.txt')
    open(plan, 'w').write('\n'.join(L) + '\n')
    agentlog = R.load_state()['agentlog']
    k0 = S.klen()
    R.peer('r166r1', plan, ['--duration', '260'])
    time.sleep(90)
    k = S.kcd_lines(r'WO166-AMNESTY|stopFight|Skirmish event', k0)
    a = open(agentlog, encoding='utf-8', errors='replace').read()
    res = {'amnesty_agent': re.findall(r'WO166-AMNESTY[^\n]*', a)[-3:], 'amnesty_lua': [l.strip()[:220] for l in k if 'WO166-AMNESTY' in l][-3:]}
    # S1: Henry 200 m from the guard and the figure, which fight on
    hx, hy = g[0] - 200.0, g[1]
    hz = S.ground(hx, hy)
    for _ in range(3):
        live.lua('player:SetWorldPos({x=%f, y=%f, z=%f})' % (hx, hy, hz + 0.3)); time.sleep(1.5)
    since = time.strftime('%H:%M:%S')
    time.sleep(60)
    until = time.strftime('%H:%M:%S')
    nat = window_lines(live.NLOG, since, until)
    ag = agent_lines(agentlog, since, until)
    res['s1_window'] = [since, until]
    res['s1_guard_rows_out'] = sum(1 for l in ag if 'kind=NpcAttack npc=%s ' % guard in l)
    res['s1_wo138'] = [l.split('WO138 ', 1)[1].strip()[:160] for l in nat if 'WO138 sender=' in l][-2:]
    res['s1_scan_fallback'] = sum(1 for l in ag if 'WO166-SCAN fallback' in l)
    res['weather_sent'] = re.findall(r'WO166-WEATHER sent[^\n]*', a)[-2:]
    json.dump(res, open(os.path.join(live.LOGS, 'run166.r1s1.json'), 'w'), indent=1)
    print(json.dumps(res, indent=1))


def lootrun(agent_dll, corpse, n):
    """L1 in the game (joiner role): the synthetic host streams <corpse> dead (the owner-death apply kills the copy here), then n cycles."""
    R.stop('agent'); R.stop('peer')
    time.sleep(7)
    c = S.ent_pos(corpse)
    if not c: raise SystemExit('no npc ' + corpse)
    px, py = c[0] + 1.2, c[1]
    pz = S.ground(px, py)
    for _ in range(3):
        live.lua('player:SetWorldPos({x=%f, y=%f, z=%f})' % (px, py, pz + 0.3)); time.sleep(1.5)
    L = ['# WO-166 L1 (generated by run166.py): a corpse copy beside the player', 'start 5',
         'ghost %.2f %.2f %.2f 0 1 50 0.0005 30' % (px + 4.0, py, S.ground(px + 4.0, py)),
         'dead %s %.2f %.2f %.2f 0' % (corpse, c[0], c[1], c[2])]
    plan = os.path.join(live.LOGS, 'plan.run166.loot.txt')
    open(plan, 'w').write('\n'.join(L) + '\n')
    R.peer('r166loot', plan, ['--duration', '900', '--claim-host'])
    R.agent('r166loot', agent_dll, ['KCDMP_TEST_JOINER_IN_WORLD=1'])
    time.sleep(15)
    live.cmd('mp_leash off')
    time.sleep(10)
    dead = S.ask('local e=System.GetEntityByName("%s"); System.LogAlways("@TAG "..tostring(e and e.actor and e.actor:IsDead()))' % corpse, 'dd%d' % time.time_ns())
    print('corpse dead here:', dead)
    loot(n, corpse)


if __name__ == '__main__':
    v = sys.argv[1]
    if v == 'fight': fight(sys.argv[2], sys.argv[3], float(sys.argv[4]), int(sys.argv[5]), sys.argv[6] if len(sys.argv) > 6 else '', sys.argv[7] if len(sys.argv) > 7 else '')
    elif v == 'loot': loot(int(sys.argv[2]), sys.argv[3])
    elif v == 'lootrun': lootrun(sys.argv[2], sys.argv[3], int(sys.argv[4]))
    elif v == 'talk': talk(sys.argv[2])
    elif v == 'status': status()
    elif v == 'c1': c1(sys.argv[2], sys.argv[3], [int(x) for x in sys.argv[4].split(',')], int(sys.argv[5]))
    elif v == 'r1s1': r1s1(sys.argv[2])
