# Copyright (C) 2026 the Kingdom Come: Together contributors (AUTHORS). SPDX-License-Identifier: GPL-3.0-only
# GPLv3 section 7 additional terms: NOTICE. This project's own code only; Kingdom Come: Deliverance II and its
# content belong to Warhorse Studios and PLAION. Unofficial, free, not affiliated with or endorsed by them.
"""WO-148: test vectors for native/KCDMP/x64_len.h, decoded by capstone.

The vectors are generated, not taken from any game binary: random instruction
shapes (prefixes, REX, the one-byte map, 0F, 0F38, 0F3A, VEX) followed by
random bytes, each decoded once by capstone in 64-bit mode. Writes
native/tests/wo148_x64_vectors.inc: one string per vector,
"<hex bytes>|<length>|<flags>", flags r = a RIP-relative operand, b = a
relative branch, c = any control transfer; length 0 = capstone refused it.

Run from the repo root:  python3 tools/wo148/gen_x64_vectors.py
(needs `pip install capstone`; the seed is fixed, so a rerun is identical).
"""
import os
import random
import sys

import capstone
from capstone import x86

SEED = 148
COUNT = 6000
TAIL = 15          # bytes after the opcode shape, enough for any ModRM/SIB/disp/imm

REPO = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
OUT = os.path.join(REPO, 'native', 'tests', 'wo148_x64_vectors.inc')

LEGACY = [0x66, 0x67, 0xF2, 0xF3, 0xF0, 0x2E, 0x36, 0x3E, 0x26, 0x64, 0x65]
PREFIX_BYTES = set(LEGACY) | set(range(0x40, 0x50))
CONTROL_GROUPS = {capstone.CS_GRP_JUMP, capstone.CS_GRP_CALL, capstone.CS_GRP_RET,
                  capstone.CS_GRP_INT, capstone.CS_GRP_IRET}
REL_GROUP = getattr(capstone, 'CS_GRP_BRANCH_RELATIVE', 7)


def shape(rng):
    """One random instruction head: prefixes + REX + opcode bytes."""
    b = []
    r = rng.random()
    if r < 0.15:
        b.append(rng.choice(LEGACY))
    elif r < 0.20:
        b += rng.sample(LEGACY, 2)
    kind = rng.random()
    if kind < 0.45 or kind >= 0.97:
        if rng.random() < 0.5:
            b.append(0x40 | rng.randrange(16))          # REX
        op = rng.randrange(256)
        while op in PREFIX_BYTES or op in (0x0F, 0xC4, 0xC5):
            op = rng.randrange(256)
        b.append(op)
    elif kind < 0.75:
        if rng.random() < 0.5:
            b.append(0x40 | rng.randrange(16))
        b += [0x0F, rng.randrange(256)]
    elif kind < 0.82:
        if rng.random() < 0.4:
            b.append(0x40 | rng.randrange(16))
        b += [0x0F, 0x38, rng.randrange(256)]
    elif kind < 0.87:
        if rng.random() < 0.4:
            b.append(0x40 | rng.randrange(16))
        b += [0x0F, 0x3A, rng.randrange(256)]
    elif kind < 0.92:
        b = [0xC5, rng.randrange(256), rng.randrange(256)]          # VEX2 + opcode
    else:
        b = [0xC4, (rng.randrange(8) << 5) | rng.randrange(1, 4), rng.randrange(256), rng.randrange(256)]
    return b


def flags_of(insn):
    f = ''
    for o in insn.operands:
        # [eip+disp32] (a 67 prefix) is as position-dependent as [rip+disp32]
        if o.type == x86.X86_OP_MEM and o.mem.base in (x86.X86_REG_RIP, x86.X86_REG_EIP):
            f += 'r'
            break
    groups = set(insn.groups)
    if REL_GROUP in groups:
        f += 'b'
    if groups & CONTROL_GROUPS or REL_GROUP in groups:
        f += 'c'
    return f


def main():
    rng = random.Random(SEED)
    md = capstone.Cs(capstone.CS_ARCH_X86, capstone.CS_MODE_64)
    md.detail = True
    rows = []
    seen = set()
    while len(rows) < COUNT:
        head = shape(rng)
        code = bytes(head + [rng.randrange(256) for _ in range(TAIL)])
        key = code[:len(head) + 2]
        if key in seen:
            continue
        seen.add(key)
        got = list(md.disasm(code, 0x10000, count=1))
        if got:
            rows.append((code, got[0].size, flags_of(got[0])))
        else:
            rows.append((code, 0, ''))
    with open(OUT, 'w', newline='\n') as f:
        f.write('// Generated by tools/wo148/gen_x64_vectors.py (seed %d, capstone %s) -- do not edit.\n'
                % (SEED, capstone.__version__))
        f.write('// "<hex>|<capstone length, 0 = refused>|<flags: r rip-relative, b relative branch, c control>"\n')
        for code, n, fl in rows:
            f.write('"%s|%d|%s",\n' % (code.hex(), n, fl))
    ok = sum(1 for _, n, _ in rows if n)
    print('wrote %s: %d vectors, %d decoded by capstone' % (OUT, len(rows), ok))
    return 0


if __name__ == '__main__':
    sys.exit(main())
